name: share2peer-dev
services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/app/entry.sh"]
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      SERVER_PORT: 3000
    volumes:
      - .:/app
